# Generated by Django 4.1.7 on 2023-03-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fandango', '0001_squashed_0007_alter_pegoste_author_alter_pegoste_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegoste',
            options={},
        ),
    ]
